setwd('P:/Geotiff')
library(raster)
library(ggplot2)
library(car)
GEDI_Raster <- raster("GEDI_Cornwall.tif")
ESA_Raster <- raster("ESA_Resample_Mean.tif")
ICESat2_Raster <- raster("ICESat2_Resample_Mean.tif")
GEDI_Data <- as.data.frame(rasterToPoints(GEDI_Raster))
ESA_Data <- as.data.frame(rasterToPoints(ESA_Raster))
ICESat2_Data <- as.data.frame(rasterToPoints(ICESat2_Raster))
model_GEDI <- lm(GEDI_Cornwall ~ x, data = GEDI_Data)
model_ESA <- lm(ESA_Resample_Mean ~ x, data = ESA_Data)
model_ICESat2 <- lm(ICESat2_Resample_Mean ~ x, data = ICESat2_Data)
par(mfrow=c(1,3))
plot(model_GEDI$fitted.values, model_GEDI$residuals, main="GEDI Model Residuals", xlab="Fitted Values", ylab="Residuals")
abline(h=0, col="red")
plot(model_ESA$fitted.values, model_ESA$residuals, main="ESA Model Residuals", xlab="Fitted Values", ylab="Residuals")
abline(h=0, col="red")
plot(model_ICESat2$fitted.values, model_ICESat2$residuals, main="ICESat2 Model Residuals", xlab="Fitted Values", ylab="Residuals")
abline(h=0, col="red")
plot(model_ALS$fitted.values, model_ALS$residuals, main="ALS Model Residuals", xlab="Fitted Values", ylab="Residuals")
abline(h=0, col="red")
ncvTest(model_GEDI)
ncvTest(model_ESA)
ncvTest(model_ICESat2)
